name: iportfolio
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pandas
  - numpy
  - jupyterlab
  - nbclassic=0.3.1
  - pip:
    - yfinance==0.1.63
    - alpha-vantage==2.3.1
    - pyxirr==0.6.2
    - streamlit==0.86.0