name: ppa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  - pandas=1.3.*
  - numpy=1.21.*
  - matplotlib
  - jupyterlab
  - nbclassic>=0.3.*
  - pip:
    - alpha-vantage==2.3.*
    - pyxirr==0.6.*
    - streamlit==0.86.*
    - yfinance==0.1.*