name: ppa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip
  - pandas
  - numpy
  - matplotlib
  - jupyterlab
  - nbclassic>=0.3.*
  - pip:
    - alpha-vantage==2.3.*
    - pyxirr==0.6.*
    - streamlit==0.86.*
    - yfinance==0.1.*